# Standalone MongoDB to be run locally exposed through Loadbalancer Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-standalone
  labels: 
    app: mongo
    tier: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo

  template:
    metadata:
      labels:
        app: mongo
        tier: backend


    spec:
      containers:
      - name: mongo
        image: mongo
        resources:
          requests: 
            cpu: 500m
            memory: 256Mi
        ports:
        - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-standalone
  labels:
    app: mongo
    tier: backend

spec:
  type: LoadBalancer
  ports:
  - port: 27027
    targetPort: 27017
  
  selector:
    app:  mongo
    tier: backend
